/*
 * UVISION generated file: DO NOT EDIT!
 * Generated by: uVision version 5.43.1.0
 *
 * Project: 'ant_bpwr_tx_pca10040_s212' 
 * Target:  'nrf52832_xxaa' 
 */

#ifndef RTE_COMPONENTS_H
#define RTE_COMPONENTS_H



#endif /* RTE_COMPONENTS_H */
